/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Google Sans"', '"Plus Jakarta Sans"', '"DM Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'display-lg': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'headline-sm': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'headline-md': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'headline-lg': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'body-sm': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'body-md': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'body-lg': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'label-sm': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'label-md': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'label-lg': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'caption-light': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        'data-metric': ['"Google Sans"', '"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui'],
        mono: ['"DM Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        hindi: ['"Noto Sans Devanagari"', 'sans-serif'],
      },
      fontSize: {
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'caption-light': ['12px', { lineHeight: '16px', fontWeight: '300' }],
        'data-metric': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'gutter-tablet': '1.5rem',
        'gutter-desktop': '1.5rem',
        'gutter-mobile': '1rem',
        'margin-tablet': '2rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
      },
      colors: {
        // Material Design 3 tokens — source of truth from the design HTML
        surface: '#f7f9ff',
        'surface-bright': '#f7f9ff',
        'surface-dim': '#ccdcf0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#edf4ff',
        'surface-container': '#e3efff',
        'surface-container-high': '#daeafe',
        'surface-container-highest': '#d4e4f8',
        'surface-variant': '#d4e4f8',
        'on-surface': '#0d1d2b',
        'on-surface-variant': '#3d4947',
        background: '#f7f9ff',
        'on-background': '#0d1d2b',
        'on-surface-variant-ish': '#3d4947',
        primary: '#00685d',
        'primary-container': '#008376',
        'primary-fixed': '#8cf5e4',
        'primary-fixed-dim': '#6fd8c8',
        'on-primary': '#ffffff',
        'on-primary-container': '#f4fffb',
        'on-primary-fixed': '#00201c',
        'on-primary-fixed-variant': '#005048',
        'inverse-primary': '#6fd8c8',
        'surface-tint': '#006a60',
        secondary: '#9b4504',
        'secondary-container': '#fe9251',
        'secondary-fixed': '#ffdbca',
        'secondary-fixed-dim': '#ffb68e',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6e2f00',
        'on-secondary-fixed': '#331200',
        'on-secondary-fixed-variant': '#773300',
        tertiary: '#166289',
        'tertiary-container': '#387ba4',
        'tertiary-fixed': '#c8e6ff',
        'tertiary-fixed-dim': '#8fcdfa',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fcfcff',
        'on-tertiary-fixed': '#001e2f',
        'on-tertiary-fixed-variant': '#004c6e',
        outline: '#6d7a77',
        'outline-variant': '#bcc9c6',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#233241',
        'inverse-on-surface': '#e8f1ff',
        brand: '#2A9D8F',
        // Legacy brand tokens remapped to the M3 palette so all pages inherit the new theme
        canvas: '#f7f9ff',
        evergreen: '#0d1d2b',
        terracotta: {
          DEFAULT: '#00685d',
          dark: '#008376',
        },
        amber: '#fe9251',
        forest: '#008376',
        linen: '#bcc9c6',
        sand: '#edf4ff',
        wash: {
          muted: '#e3efff',
          forest: '#d4e4f8',
          amber: '#ffe3cf',
          terracotta: '#ffdad6',
        },
        mutedtext: '#3d4947',
        disabledbg: '#e3efff',
        kisan: {
          50: '#f4fffb',
          100: '#e6f6f2',
          200: '#bfe2d9',
          300: '#8fcfc2',
          400: '#4fb3a3',
          500: '#2A9D8F',
          600: '#008376',
          700: '#00685d',
          800: '#004d45',
          900: '#00352f',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'sm': '0 1px 2px rgba(0,0,0,0.08)',
        card: '0 1px 3px rgba(20, 40, 27, 0.04), 0 4px 12px rgba(20, 40, 27, 0.03)',
        'card-hover': '0 4px 8px rgba(20, 40, 27, 0.06), 0 12px 24px rgba(20, 40, 27, 0.05)',
        modal: '0 12px 36px rgba(20, 40, 27, 0.12), 0 4px 12px rgba(20, 40, 27, 0.06)',
      },
      keyframes: {
        'page-in': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'amber-glow': {
          '0%': { boxShadow: '0 0 0 4px rgba(232, 168, 56, 0.22)' },
          '100%': { boxShadow: '0 0 0 4px rgba(232, 168, 56, 0)' },
        },
      },
      animation: {
        'page-in': 'page-in 200ms cubic-bezier(0.16, 1, 0.3, 1) both',
        shimmer: 'shimmer 1.8s infinite ease-in-out',
        'amber-glow': 'amber-glow 800ms ease-out',
      },
    },
  },
  plugins: [],
};