# Multilingual AI Chatbot blueprint definitions using Groq API (LLaMA 3.1 8B) & Voice Engine
import os
import logging
from flask import Blueprint, request
from groq import Groq
from app.utils.response import success_response, error_response
from app.utils.voice_engine import VoiceEngine

chatbot_bp = Blueprint('chatbot', __name__)
logger = logging.getLogger(__name__)
voice_engine = VoiceEngine()

# Lazy initialization of Groq client
def get_groq_client():
    api_key = os.getenv('GROQ_API_KEY')
    if not api_key or api_key.startswith('your_'):
        return None
    try:
        return Groq(api_key=api_key)
    except Exception as e:
        logger.error(f"Failed to initialize Groq client: {e}")
        return None

SYSTEM_PROMPTS = {
    'farmer': {
        'en': "You are Kisan Mitra, a friendly AI assistant for Kisan Connect marketplace. Help farmers with: listing produce, understanding demand forecasts, checking crop prices, logistics. Keep responses under 3 sentences. Be warm and simple.",
        'hi': "आप Kisan Mitra हैं - Kisan Connect marketplace के लिए एक मित्रवत AI सहायक। किसानों की मदद करें: अनाज/सब्जी लिस्टिंग, मांग पूर्वानुमान, कीमतें, लॉजिस्टिक्स। जवाब 3 वाक्यों में दें। सरल और मित्रवत रहें।",
        'mr': "तुमचे नाव Kisan Mitra आहे - Kisan Connect डिजिटल मार्केटप्लेसचे AI सहाय्यक. शेतकऱ्यांना मदत करा: पिकांची नोंदणी/लिस्टिंग, बाजारभाव, मागणी अंदाज आणि लॉजिस्टिक्स. ३ वाक्यांत साधे आणि आदराचे उत्तर द्या."
    },
    'consumer': {
        'en': "You are Kisan Mitra, helping consumers on Kisan Connect find fresh farm produce. Help with: browsing products, placing orders, tracking delivery, returns. Keep responses under 3 sentences. Be short and helpful.",
        'hi': "आप Kisan Mitra हैं - Kisan Connect पर खरीदारों की मदद करते हैं। ताजा उत्पाद खोजना, ऑर्डर करना, डिलीवरी ट्रैक करना में सहायता करें। 3 वाक्यों में जवाब दें। संक्षिप्त और सहायक रहें।",
        'mr': "तुमचे नाव Kisan Mitra आहे - Kisan Connect वर ग्राहकांना मदत करा: ताज्या पिकांचा शोध, ऑर्डर करणे, डिलिव्हरी ट्रॅकिंग आणि परतावा धोरण. ३ वाक्यांत संक्षिप्त उत्तर द्या."
    },
    'logistics': {
        'en': "You are Kisan Mitra, helping logistics partners on Kisan Connect. Help with: driver assignments, route delivery questions, proof of delivery. Keep responses under 3 sentences.",
        'hi': "आप Kisan Mitra हैं - Kisan Connect के लॉजिस्टिक्स पार्टनर्स की सहायता करते हैं। असाइनमेंट, रूट डिलीवरी, डिलीवरी प्रूफ में मदद करें। 3 वाक्यों में जवाब दें।",
        'mr': "तुमचे नाव Kisan Mitra आहे - Kisan Connect च्या ड्रायव्हर्स आणि लॉजिस्टिक्स भागीदारांना मदत करा: डिलिव्हरी असाइनमेंट, रूट आणि डिलिव्हरी प्रूफ. ३ वाक्यांत उत्तर द्या."
    },
    'default': {
        'en': "You are Kisan Mitra, AI assistant for Kisan Connect direct farm-to-consumer marketplace. Be helpful, concise, and friendly. Keep responses under 3 sentences.",
        'hi': "आप Kisan Mitra हैं - Kisan Connect marketplace के AI सहायक। सहायक, संक्षिप्त और मित्रवत रहें। 3 वाक्यों में जवाब दें।",
        'mr': "तुमचे नाव Kisan Mitra आहे - Kisan Connect चे AI सहाय्यक. नम्र, संक्षिप्त आणि मदतगार राहा. ३ वाक्यांत उत्तर द्या."
    }
}

@chatbot_bp.route('/query', methods=['POST'])
def chat():
    """
    POST /ai/chatbot/query
    Payload: { "message": "...", "language": "mr"|"hi"|"en", "user_role": "farmer", "conversation_history": [] }
    Returns AI response generated by LLaMA 3.1 8B via Groq API in English, Hindi, or Marathi with robust fallback.
    """
    language = 'en'
    try:
        data = request.get_json()
        if not data or 'message' not in data:
            return error_response(message="Missing required field: message", status_code=400)

        message = str(data['message']).strip()
        language = str(data.get('language', 'en')).strip().lower()
        user_role = str(data.get('user_role', 'default')).strip().lower()
        conversation_history = data.get('conversation_history', [])

        # Limit history context to last 6 messages (3 turns)
        history = conversation_history[-6:] if isinstance(conversation_history, list) else []

        if not message:
            return error_response(message="Empty message content", status_code=400)

        client = get_groq_client()
        if not client:
            fallback_map = {
                'mr': "मला सध्या तांत्रिक अडचण येत आहे. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.",
                'hi': "मुझे अभी तकनीकी समस्या है। कृपया बाद में प्रयास करें。",
                'en': "I am currently experiencing a technical connection issue. Please try again shortly."
            }
            fallback_reply = fallback_map.get(language, fallback_map['en'])
            return success_response(data={'response': fallback_reply, 'is_fallback': True}, message="Fallback response served")

        role_dict = SYSTEM_PROMPTS.get(user_role, SYSTEM_PROMPTS['default'])
        system_prompt = role_dict.get(language, role_dict['en'])

        messages = [{'role': 'system', 'content': system_prompt}]
        for msg in history:
            if isinstance(msg, dict) and 'role' in msg and 'content' in msg:
                messages.append({'role': msg['role'], 'content': str(msg['content'])})
        messages.append({'role': 'user', 'content': message})

        groq_response = client.chat.completions.create(
            model='llama-3.1-8b-instant',
            messages=messages,
            max_tokens=300,
            temperature=0.7
        )

        reply = groq_response.choices[0].message.content.strip()
        return success_response(data={'response': reply, 'is_fallback': False}, message="Chatbot query processed successfully")

    except Exception as e:
        logger.error(f"Chatbot query error: {str(e)}")
        fallback_map = {
            'mr': "मला सध्या तांत्रिक अडचण येत आहे. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.",
            'hi': "मुझे अभी तकनीकी समस्या है। कृपया बाद में प्रयास करें。",
            'en': "I am currently experiencing a technical connection issue. Please try again shortly."
        }
        fallback_reply = fallback_map.get(language, fallback_map['en'])
        return success_response(data={'response': fallback_reply, 'is_fallback': True}, message="Fallback response served")

@chatbot_bp.route('/voice', methods=['POST'])
def voice_chat():
    """
    POST /ai/chatbot/voice
    Supports real-time microphone text transcript or audio stream processing.
    Returns generated response text along with Sarvam/WebSpeech TTS metadata.
    """
    try:
        data = request.get_json() or {}
        message = data.get('transcript', data.get('message', '')).strip()
        language = str(data.get('language', 'hi')).strip().lower()
        user_role = str(data.get('user_role', 'default')).strip().lower()

        if not message:
            return error_response(message="Missing transcript or audio message", status_code=400)

        # Generate text response via LLM
        client = get_groq_client()
        if client:
            role_dict = SYSTEM_PROMPTS.get(user_role, SYSTEM_PROMPTS['default'])
            system_prompt = role_dict.get(language, role_dict['en'])
            messages = [{'role': 'system', 'content': system_prompt}, {'role': 'user', 'content': message}]
            groq_response = client.chat.completions.create(
                model='llama-3.1-8b-instant',
                messages=messages,
                max_tokens=300,
                temperature=0.7
            )
            response_text = groq_response.choices[0].message.content.strip()
        else:
            response_text = "नमस्कार! मी किसान मित्र आहे. मी तुम्हाला कशी मदत करू शकतो?"

        # Attempt server-side Sarvam TTS if configured
        audio_b64 = voice_engine.process_tts(response_text, language=language)

        return success_response(data={
            "transcript": message,
            "response_text": response_text,
            "audio_base64": audio_b64,
            "language": language,
            "tts_provider": "sarvam" if audio_b64 else "web_speech_api"
        }, message="Voice chat processed successfully")

    except Exception as e:
        logger.error(f"Voice chat endpoint error: {str(e)}")
        return error_response(message=f"Failed to process voice query: {str(e)}", status_code=500)
